type backgrounds = 'forest' | 'forest'
type characters = 'howard' | 'paladin'
type fonts = 'm5x7'
type items = 'campfire'
type levels = 'minibattle' | 'overworld' | 'tavern'
type tilesets = 'Compilation-Building' | 'GB-LandTileset' | 'GB-Trees-and-Mountains' | 'Minifantasy_ForgottenPlainsProps' | 'Minifantasy_ForgottenPlainsTiles' | 'Minifantasy_TownsIIBrickBuildingOutdoorTileset' | 'Minifantasy_TownsIIWoodenPlankBuildingOutdoorTileset' | 'Minifantasy_TownsProps' | 'Minifantasy_TownsPropsShadows' | 'Minifantasy_TownsTileset' | 'Minifantasy_TownsTilesetShadows' | 'TavernIndoorAll' | 'TavernIndoorAllShadows' | 'Tents' | 'TentsShadows' | 'Universal-Road-Tileset' | 'WallOfTrees' | 'WallOfTreesShadows'
type ui = 'frameBig' | 'framedisplay' | 'GUI' | 'healthbar' | 'healthfull' | 'textbox'
