type animations = 'explosion-1' | 'explosion-2' | 'explosion-4' | 'explosion-6' | 'portalEnd' | 'portalMiddle' | 'portalStart'
type backgrounds = 'forest'
type characters = 'angelOfDeath' | 'bandit' | 'bandit2' | 'goblin' | 'howard' | 'orc' | 'paladin'
type fonts = 'm5x7'
type items = 'campfire'
type levels = 'minibattle' | 'overworld' | 'tavern'
type tilesets = 'Compilation-Building' | 'GB-LandTileset' | 'GB-Trees-and-Mountains' | 'Minifantasy_ForgottenPlainsProps' | 'Minifantasy_ForgottenPlainsTiles' | 'Minifantasy_TownsIIBrickBuildingOutdoorTileset' | 'Minifantasy_TownsIIWoodenPlankBuildingOutdoorTileset' | 'Minifantasy_TownsProps' | 'Minifantasy_TownsPropsShadows' | 'Minifantasy_TownsTileset' | 'Minifantasy_TownsTilesetShadows' | 'TavernIndoorAll' | 'TavernIndoorAllShadows' | 'Tents' | 'TentsShadows' | 'TileasetAndPremadeZiggurats' | 'TileasetAndPremadeZigguratsProps' | 'TileasetAndPremadeZigguratsPropsShadows' | 'TileasetAndPremadeZigguratsShadows' | 'Universal-Road-Tileset' | 'WallOfTrees' | 'WallOfTreesShadows'
type ui = 'boots' | 'frameBig' | 'framedisplay' | 'healthbar' | 'healthfull' | 'textbox'
