type ui = 'healthfull' | 'healthbar' | 'framedisplay' | 'frameBig'
type levels = 'overworld' | 'minibattle' | 'gitBattle' | 'battle3' | 'battle2' | 'battle'
type fonts = 'm5x7'
type characters = 'MiniPrinceMan' | 'MiniGoblinThief' | 'MiniGoblin' | 'Minifantasy_CreaturesOrcBaseAnimations' | 'Minifantasy_CreaturesHumanBaseAnimations'
type backgrounds = 'forest'
type tilesets = 'Universal-Road-Tileset' | 'TilesetNature' | 'TilesetHouse' | 'TilesetFloorDetail' | 'TilesetFloor' | 'TilesetElement' | 'RVTerrain' | 'RVNature' | 'RVDecoration' | 'Minifantasy_ForgottenPlainsTiles' | 'Minifantasy_ForgottenPlainsProps' | 'GB-Trees-and-Mountains' | 'GB-LandTileset' | 'free_campfire' | 'Compilation-Building' | 'atlas' | 'Assets'
